class AppReq:
    """
    Class to parse application requirements.
    """    
    def __init__(self):
        pass

    def eval_app_req_with_vars(self, lambda_str, dicts):
        """
        Executes the lambda expression generated by parse_app_req_params (moved into Sardou lib)
        on a list of dictionaries (dicts).
        Returns a list of booleans indicating which dicts satisfy the expression.
        """
        func = eval(lambda_str)
        return [func(d) for d in dicts]
